name: Hourly EMA200 Scanner (Market Hours)

on:
  schedule:
    - cron: '0 4 * * 1-5'   # 09:30 IST
    - cron: '0 5 * * 1-5'   # 10:30 IST
    - cron: '0 6 * * 1-5'   # 11:30 IST
    - cron: '0 7 * * 1-5'   # 12:30 IST
    - cron: '0 8 * * 1-5'   # 13:30 IST
    - cron: '0 9 * * 1-5'   # 14:30 IST
    - cron: '0 10 * * 1-5'  # 15:30 IST
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install tradingview_ta requests

    - name: Run EMA200 Scanner
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python -u main.py  # 🔁 Replace with your actual filename
